apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    app: mongodb
data:
  # refering a serivce here directly instead of any statically typed url.
  mongo-url: mongodb-service
